@echo off
title Update and Restart Dove QMS
echo Stopping Server...
call stop_server.bat
echo.
echo Building latest version...
echo This may take a minute...
cmd /c npm run build
echo.
echo Starting Server...
start_server.bat
pause
